/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Natalia
 */
public class agregarVenta extends javax.swing.JFrame {
    ControlVenta controlVenta = new ControlVenta();
    ControlCarritoVen controlCarritoVen = new ControlCarritoVen();
    ControlCotizacion controlCotizacion = new ControlCotizacion();
    ControlCarritoCot controlCarritoCot = new ControlCarritoCot();
    String usuario;
    String sede;
    DefaultTableModel tabla;
    Date date = new Date();
    
    /**
     * Creates new form agregarVenta
     */
    public agregarVenta(String usuario, String sede) {
        this.usuario = usuario;
        this.sede = sede;
        initComponents();
        setDefaultCloseOperation(0);
        this.setLocationRelativeTo(null);
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        this.cedulaVen.setText(usuario);
        this.fecha.setText(dateFormat.format(date));
        this.NVenta.setText(controlVenta.generarIdVenta());
        cargarCotizaciones();
    }
    
    void cargarCotizaciones(){
        ArrayList cotizaciones = controlCotizacion.cargarCotizaciones();
        for(int i = 0; i < cotizaciones.size(); i++) {
            this.cotizaciones.addItem(cotizaciones.get(i).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        agregarProducto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdetbol = new javax.swing.JTable();
        eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        consultar = new javax.swing.JButton();
        NVenta = new javax.swing.JTextField();
        cotizaciones = new javax.swing.JComboBox<>();
        Calcular = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        fecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cedulaVen = new javax.swing.JLabel();
        jLabelCrearVenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 190, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 130, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 190, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 502, 160, 10));

        salir.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CERRAR2.png"))); // NOI18N
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CERRAR.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 150, 40));

        jLabel3.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel3.setText("Total:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 50, -1));

        total.setEditable(false);
        total.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(102, 0, 102));
        total.setBorder(null);
        total.setOpaque(false);
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 160, -1));

        agregarProducto.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        agregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AGREGARPRODUCTOS.png"))); // NOI18N
        agregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarProducto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AGREGARPRODUCTOS2.png"))); // NOI18N
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(agregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 200, 25));

        tbdetbol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));
        tbdetbol.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        tbdetbol.setForeground(new java.awt.Color(102, 0, 102));
        tbdetbol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO UNIDAD", "SUBTOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbdetbol.setPreferredSize(new java.awt.Dimension(400, 400));
        tbdetbol.setSelectionBackground(new java.awt.Color(102, 0, 102));
        jScrollPane2.setViewportView(tbdetbol);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 770, 170));

        eliminar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ELIMINARPRODUCTOS.png"))); // NOI18N
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ELIMINARPRODUCTOS2.png"))); // NOI18N
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 200, 25));

        jLabel5.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel5.setText("N° Cotización:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel1.setText("N° Venta:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        consultar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CARGARCOTIZACION2.png"))); // NOI18N
        consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CARGARCOTIZACION.png"))); // NOI18N
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        jPanel1.add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 200, 25));

        NVenta.setEditable(false);
        NVenta.setBackground(new java.awt.Color(255, 255, 255));
        NVenta.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        NVenta.setBorder(null);
        NVenta.setOpaque(false);
        NVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVentaActionPerformed(evt);
            }
        });
        NVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NVentaKeyTyped(evt);
            }
        });
        jPanel1.add(NVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 111, -1));

        cotizaciones.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cotizaciones.setForeground(new java.awt.Color(102, 0, 102));
        cotizaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cotizaciones.setOpaque(false);
        jPanel1.add(cotizaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 120, -1));

        Calcular.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CALCULARMONTOS.png"))); // NOI18N
        Calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calcular.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CALCULARMONTOS2.png"))); // NOI18N
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        jPanel1.add(Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 200, 25));

        Agregar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/REGISTRARVENTA.png"))); // NOI18N
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/REGISTRARVENTA2.png"))); // NOI18N
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 200, 25));

        fecha.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        fecha.setText(" ");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 190, -1));

        jLabel2.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel2.setText("Cedula vendedor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel4.setText("fecha de registro:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        cedulaVen.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cedulaVen.setText(" ");
        jPanel1.add(cedulaVen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 190, -1));

        jLabelCrearVenta.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabelCrearVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/REGISTRODEVENTASFONDO.png"))); // NOI18N
        jPanel1.add(jLabelCrearVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NVentaActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        if(tbdetbol.getRowCount()<1){
            JOptionPane.showMessageDialog(this, "Seleccione al menos un producto");
        }
        else{
            String pre;
            String can;
            double precio;
            int cantidad;
            double subtotal=0;
            double precioTotal=0;
        
            for(int i=0;i<tbdetbol.getRowCount();i++){
            pre=tbdetbol.getValueAt(i, 3).toString();
            can=tbdetbol.getValueAt(i, 2).toString();
            precio=Double.parseDouble(pre);
            cantidad=Integer.parseInt(can);
            subtotal = precio*cantidad;
            precioTotal = precioTotal +subtotal;
            
            tbdetbol.setValueAt(subtotal, i, 4);
            
        }
            total.setText("" + precioTotal);
        }
    }//GEN-LAST:event_CalcularActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Vendedor vendedor = new Vendedor(usuario);
        vendedor.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        total.setText("");
        Inventario inventario = new Inventario();
        inventario.setVisible(true);
    }//GEN-LAST:event_agregarProductoActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbdetbol.getModel();
        int fila = tbdetbol.getSelectedRow();
        if(fila>=0) {
            model.removeRow(fila);
            total.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        try{
            if((NVenta.getText().equals(""))||(total.getText().equals(""))){
            JOptionPane.showMessageDialog(this, "Ingrese el numero de la venta o realice el calculo del monto");
            }
            else{
                boolean permitirVenta = true;
                String producto = "";
                for(int i=0; i<this.tbdetbol.getRowCount(); i++){
                    String codigo = tbdetbol.getValueAt(i, 0).toString();
                    String cantidad = tbdetbol.getValueAt(i, 2).toString();
                    int peticion = Integer.parseInt(cantidad);
                    
                    if(controlVenta.verificarVenta(codigo, peticion)){
                        
                    }else{
                        permitirVenta = false;
                        producto = producto + "\n" + codigo;
                    }
                }
                if(!permitirVenta){
                    JOptionPane.showMessageDialog(this, "No hay suficientes unidades de los siguientes productos: " + producto);
                }else{
                    String id_venta = this.NVenta.getText();
                    String id_vendedor = this.cedulaVen.getText();
                    String fecha = this.fecha.getText();
                    float total = Float.parseFloat(this.total.getText());

                    String mensaje = controlVenta.agregarVenta(id_venta, id_vendedor, fecha, total, sede);
                    
                    if (mensaje.equals("Venta creada correctamente")){
                        for(int i=0; i<this.tbdetbol.getRowCount(); i++){
                            
                            String codigo = tbdetbol.getValueAt(i, 0).toString();
                            String cantidad = tbdetbol.getValueAt(i, 2).toString();
                            String valor = tbdetbol.getValueAt(i, 4).toString();
                            int peticion = Integer.parseInt(cantidad);
                            float subtotal = Float.parseFloat(valor);

                            controlCarritoVen.agregarProducto(id_venta, codigo, peticion, subtotal);
                            controlCarritoVen.restarProducto(codigo, peticion);
                        }
                        String [] Titulo = {"CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO UNIDAD", "SUBTOTAL"};
                        DefaultTableModel newTabla = new DefaultTableModel(null,Titulo);
                        this.tbdetbol.setModel(newTabla);
                        this.total.setText("");
                        this.NVenta.setText("");
                        this.NVenta.setText(controlVenta.generarIdVenta());
                    }
                
                    JOptionPane.showMessageDialog(this, mensaje);
                }
            }   
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
        }
        
    }//GEN-LAST:event_AgregarActionPerformed

    private void NVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NVentaKeyReleased
        // TODO add your handling co
    }//GEN-LAST:event_NVentaKeyReleased

    private void NVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NVentaKeyTyped
        // TODO add your handling code here:
        char id_venta = evt.getKeyChar();
        if(Character.isLetter(id_venta)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo caracteres numericos");
        }
    }//GEN-LAST:event_NVentaKeyTyped

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        try{
            total.setText("");
            String id = this.cotizaciones.getSelectedItem().toString();
            tabla = this.controlCarritoCot.cargarProductosCot(id);
            this.tbdetbol.setModel(tabla);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
        }

    }//GEN-LAST:event_consultarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField NVenta;
    private javax.swing.JButton agregarProducto;
    private javax.swing.JLabel cedulaVen;
    private javax.swing.JButton consultar;
    private javax.swing.JComboBox<String> cotizaciones;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCrearVenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton salir;
    public static javax.swing.JTable tbdetbol;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
