/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Natalia
 */
public class agregarCotizacion extends javax.swing.JFrame {
    ControlCotizacion controlCotizacion = new ControlCotizacion();
    ControlCarritoCot controlCarritoCot = new ControlCarritoCot();
    String usuario;
    Date date = new Date();
    /**
     * Creates new form agregarCotizacion
     */
    public agregarCotizacion(String usuario) {
        this.usuario = usuario;
        initComponents();
        setDefaultCloseOperation(0);
        this.setLocationRelativeTo(null);
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        this.cedulaVen.setText(usuario);
        this.fecha.setText(dateFormat.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Agregar = new javax.swing.JButton();
        fecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cedulaVen = new javax.swing.JLabel();
        agregarProducto = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NCotizacion = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdetbol = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar.setText("Registrar cotizacion");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 200, 25));

        fecha.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        fecha.setForeground(new java.awt.Color(102, 0, 102));
        fecha.setText(" ");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 150, 25));

        jLabel2.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel2.setText("Cedula vendedor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 150, 25));

        jLabel4.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel4.setText("Fecha de registro:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 150, 25));

        cedulaVen.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cedulaVen.setForeground(new java.awt.Color(102, 0, 102));
        cedulaVen.setText(" ");
        jPanel1.add(cedulaVen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 150, 25));

        agregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AGREGARPRODUCTOS.png"))); // NOI18N
        agregarProducto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AGREGARPRODUCTOS2.png"))); // NOI18N
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(agregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 200, 25));

        eliminar.setText("Eliminar producto");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 200, 25));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel1.setText("N° Cotizacion:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, 25));

        NCotizacion.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        NCotizacion.setForeground(new java.awt.Color(102, 0, 102));
        NCotizacion.setBorder(null);
        NCotizacion.setOpaque(false);
        NCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NCotizacionActionPerformed(evt);
            }
        });
        NCotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NCotizacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NCotizacionKeyTyped(evt);
            }
        });
        jPanel1.add(NCotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 150, 25));

        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        jPanel1.add(Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 200, 25));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CERRAR2.png"))); // NOI18N
        salir.setText("Cerrar");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CERRAR.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 130, 40));

        jLabel5.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel5.setText("Total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 60, 25));

        total.setEditable(false);
        total.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(102, 0, 102));
        total.setBorder(null);
        total.setOpaque(false);
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 150, 25));

        tbdetbol.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        tbdetbol.setForeground(new java.awt.Color(102, 0, 102));
        tbdetbol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO UNIDAD", "SUBTOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbdetbol.setPreferredSize(new java.awt.Dimension(500, 700));
        tbdetbol.setSelectionBackground(new java.awt.Color(102, 0, 102));
        jScrollPane2.setViewportView(tbdetbol);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 830, 170));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Registro de cotizaciones");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 170, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 170, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 170, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 170, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        try{
            if((NCotizacion.getText().equals(""))||(total.getText().equals(""))){
                JOptionPane.showMessageDialog(this, "Ingrese el numero de la cotizacion o realice el calculo del monto");
            }
            else{
                String id_cotizacion = this.NCotizacion.getText();
                String id_vendedor = this.cedulaVen.getText();
                String fecha = this.fecha.getText();
                float total = Float.parseFloat(this.total.getText());

                String mensaje = controlCotizacion.agregarCotizacion(id_cotizacion, id_vendedor, fecha, total);
                
                if (mensaje.equals("Cotizacion creada correctamente")){
                    for(int i=0; i<this.tbdetbol.getRowCount(); i++){

                        String codigo = tbdetbol.getValueAt(i, 0).toString();
                        String cantidad = tbdetbol.getValueAt(i, 2).toString();
                        String valor = tbdetbol.getValueAt(i, 4).toString();
                        int peticion = Integer.parseInt(cantidad);
                        float subtotal = Float.parseFloat(valor);

                        controlCarritoCot.agregarProducto(id_cotizacion, codigo, peticion, subtotal);
                    }
                }

                JOptionPane.showMessageDialog(this, mensaje);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
        }

    }//GEN-LAST:event_AgregarActionPerformed

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        // TODO add your handling code here:
        InventarioCot inventarioCot = new InventarioCot();
        inventarioCot.setVisible(true);
    }//GEN-LAST:event_agregarProductoActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbdetbol.getModel();
        int fila = tbdetbol.getSelectedRow();
        if(fila>=0) {
            model.removeRow(fila);
            total.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void NCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NCotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NCotizacionActionPerformed

    private void NCotizacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NCotizacionKeyReleased
        // TODO add your handling co
    }//GEN-LAST:event_NCotizacionKeyReleased

    private void NCotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NCotizacionKeyTyped
        // TODO add your handling code here:
        char id_venta = evt.getKeyChar();
        if(Character.isLetter(id_venta)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo caracteres numericos");
        }
    }//GEN-LAST:event_NCotizacionKeyTyped

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        if(tbdetbol.getRowCount()<1){
            JOptionPane.showMessageDialog(this, "Seleccione al menos un producto");
        }
        else{
            String pre;
            String can;
            double precio;
            int cantidad;
            double subtotal=0;
            double precioTotal=0;

            for(int i=0;i<tbdetbol.getRowCount();i++){
                pre=tbdetbol.getValueAt(i, 3).toString();
                can=tbdetbol.getValueAt(i, 2).toString();
                precio=Double.parseDouble(pre);
                cantidad=Integer.parseInt(can);
                subtotal = precio*cantidad;
                precioTotal = precioTotal +subtotal;

                tbdetbol.setValueAt(subtotal, i, 4);

            }
            total.setText("" + precioTotal);
        }
    }//GEN-LAST:event_CalcularActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Vendedor vendedor = new Vendedor(usuario);
        vendedor.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField NCotizacion;
    private javax.swing.JButton agregarProducto;
    private javax.swing.JLabel cedulaVen;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton salir;
    public static javax.swing.JTable tbdetbol;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
