/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Natalia
 */
public class agregarVenta extends javax.swing.JFrame {
    ControlVenta controlVenta = new ControlVenta();
    ControlCarritoVen controlCarritoVen = new ControlCarritoVen();
    ControlCotizacion controlCotizacion = new ControlCotizacion();
    ControlCarritoCot controlCarritoCot = new ControlCarritoCot();
    String usuario;
    String sede;
    DefaultTableModel tabla;
    Date date = new Date();
    
    /**
     * Creates new form agregarVenta
     */
    public agregarVenta(String usuario, String sede) {
        this.usuario = usuario;
        this.sede = sede;
        initComponents();
        setDefaultCloseOperation(0);
        this.setLocationRelativeTo(null);
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        this.cedulaVen.setText(usuario);
        this.fecha.setText(dateFormat.format(date));
        cargarCotizaciones();
    }
    
    void cargarCotizaciones(){
        ArrayList cotizaciones = controlCotizacion.cargarCotizaciones();
        for(int i = 0; i < cotizaciones.size(); i++) {
            this.cotizaciones.addItem(cotizaciones.get(i).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCrearVenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdetbol = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        NVenta = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        fecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cedulaVen = new javax.swing.JLabel();
        agregarProducto = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        consultar = new javax.swing.JButton();
        cotizaciones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelCrearVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCrearVenta.setText("Registro de ventas");

        jLabel2.setText("Cedula vendedor:");

        jLabel3.setText("Total:");

        total.setEditable(false);

        tbdetbol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO UNIDAD", "SUBTOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbdetbol);

        jLabel1.setText("N° Venta:");

        NVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVentaActionPerformed(evt);
            }
        });
        NVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NVentaKeyTyped(evt);
            }
        });

        Calcular.setText("Calcular monto");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        Agregar.setText("Registrar venta");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        salir.setText("Cerrar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fecha.setText(" ");

        jLabel4.setText("fecha de registro:");

        cedulaVen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cedulaVen.setText(" ");

        agregarProducto.setText("Agregar producto");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar producto");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel5.setText("N° Cotización:");

        consultar.setText("Cargar cotizacion");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fecha))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cedulaVen))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cotizaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(consultar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(agregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Agregar)))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCrearVenta)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCrearVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cotizaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(consultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cedulaVen))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fecha)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Calcular)
                            .addComponent(agregarProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Agregar)
                            .addComponent(eliminar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NVentaActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        if(tbdetbol.getRowCount()<1){
            JOptionPane.showMessageDialog(this, "Seleccione al menos un producto");
        }
        else{
            String pre;
            String can;
            double precio;
            int cantidad;
            double subtotal=0;
            double precioTotal=0;
        
            for(int i=0;i<tbdetbol.getRowCount();i++){
            pre=tbdetbol.getValueAt(i, 3).toString();
            can=tbdetbol.getValueAt(i, 2).toString();
            precio=Double.parseDouble(pre);
            cantidad=Integer.parseInt(can);
            subtotal = precio*cantidad;
            precioTotal = precioTotal +subtotal;
            
            tbdetbol.setValueAt(subtotal, i, 4);
            
        }
            total.setText("" + precioTotal);
        }
    }//GEN-LAST:event_CalcularActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Vendedor vendedor = new Vendedor(usuario);
        vendedor.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        total.setText("");
        Inventario inventario = new Inventario();
        inventario.setVisible(true);
    }//GEN-LAST:event_agregarProductoActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbdetbol.getModel();
        int fila = tbdetbol.getSelectedRow();
        if(fila>=0) {
            model.removeRow(fila);
            total.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        try{
            if((NVenta.getText().equals(""))||(total.getText().equals(""))){
            JOptionPane.showMessageDialog(this, "Ingrese el numero de la venta o realice el calculo del monto");
            }
            else{
                boolean permitirVenta = true;
                String producto = "";
                for(int i=0; i<this.tbdetbol.getRowCount(); i++){
                    String codigo = tbdetbol.getValueAt(i, 0).toString();
                    String cantidad = tbdetbol.getValueAt(i, 2).toString();
                    int peticion = Integer.parseInt(cantidad);
                    
                    if(controlVenta.verificarVenta(codigo, peticion)){
                        
                    }else{
                        permitirVenta = false;
                        producto = producto + "\n" + codigo;
                    }
                }
                if(!permitirVenta){
                    JOptionPane.showMessageDialog(this, "No hay suficientes unidades de los siguientes productos: " + producto);
                }else{
                    String id_venta = this.NVenta.getText();
                    String id_vendedor = this.cedulaVen.getText();
                    String fecha = this.fecha.getText();
                    float total = Float.parseFloat(this.total.getText());

                    String mensaje = controlVenta.agregarVenta(id_venta, id_vendedor, fecha, total, sede);
                    
                    if (mensaje.equals("Venta creada correctamente")){
                        for(int i=0; i<this.tbdetbol.getRowCount(); i++){
                            
                            String codigo = tbdetbol.getValueAt(i, 0).toString();
                            String cantidad = tbdetbol.getValueAt(i, 2).toString();
                            String valor = tbdetbol.getValueAt(i, 4).toString();
                            int peticion = Integer.parseInt(cantidad);
                            float subtotal = Float.parseFloat(valor);

                            controlCarritoVen.agregarProducto(id_venta, codigo, peticion, subtotal);
                            controlCarritoVen.restarProducto(codigo, peticion);
                        }
                        String [] Titulo = {"CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO UNIDAD", "SUBTOTAL"};
                        DefaultTableModel newTabla = new DefaultTableModel(null,Titulo);
                        this.tbdetbol.setModel(newTabla);
                        this.total.setText("");
                        this.NVenta.setText("");
                    }
                
                    JOptionPane.showMessageDialog(this, mensaje);
                }
            }   
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
        }
        
    }//GEN-LAST:event_AgregarActionPerformed

    private void NVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NVentaKeyReleased
        // TODO add your handling co
    }//GEN-LAST:event_NVentaKeyReleased

    private void NVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NVentaKeyTyped
        // TODO add your handling code here:
        char id_venta = evt.getKeyChar();
        if(Character.isLetter(id_venta)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo caracteres numericos");
        }
    }//GEN-LAST:event_NVentaKeyTyped

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        try{
            total.setText("");
            String id = this.cotizaciones.getSelectedItem().toString();
            tabla = this.controlCarritoCot.cargarProductosCot(id);
            this.tbdetbol.setModel(tabla);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
        }

    }//GEN-LAST:event_consultarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField NVenta;
    private javax.swing.JButton agregarProducto;
    private javax.swing.JLabel cedulaVen;
    private javax.swing.JButton consultar;
    private javax.swing.JComboBox<String> cotizaciones;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCrearVenta;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton salir;
    public static javax.swing.JTable tbdetbol;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
