/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Natalia
 */
public class consultarCotizacion extends javax.swing.JFrame {
    String usuario;
    DefaultTableModel tabla;
    ControlCotizacion controlCotizacion = new ControlCotizacion();
    ControlCarritoCot controlCarritoCot = new ControlCarritoCot();
    /**
     * Creates new form consultarCotizacion
     */
    public consultarCotizacion(String usuario) {
        this.usuario = usuario;
        initComponents();
        setDefaultCloseOperation(0);
        this.setLocationRelativeTo(null);
        cargarCotizaciones();
    }
    
    void cargarCotizaciones(){
        ArrayList cotizaciones = controlCotizacion.cargarCotizaciones();
        for(int i = 0; i < cotizaciones.size(); i++) {
            this.cotizaciones.addItem(cotizaciones.get(i).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelTituloConsultarCotizacion = new javax.swing.JLabel();
        cotizaciones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cotizacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vendedor = new javax.swing.JTextField();
        consultar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        productos = new javax.swing.JTable();
        cerrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 60, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 170, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 160, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 160, 10));

        jLabelTituloConsultarCotizacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTituloConsultarCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CONSULTARCOTIZACION.png"))); // NOI18N
        jPanel1.add(jLabelTituloConsultarCotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -5, 800, 90));

        cotizaciones.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cotizaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cotizaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 80, 25));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel1.setText("N° Cotización:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel2.setText("N° Cotización:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        cotizacion.setEditable(false);
        cotizacion.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cotizacion.setBorder(null);
        cotizacion.setOpaque(false);
        jPanel1.add(cotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 56, -1));

        jLabel3.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel3.setText("Cedula vendedor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        vendedor.setEditable(false);
        vendedor.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        vendedor.setBorder(null);
        vendedor.setOpaque(false);
        jPanel1.add(vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 160, -1));

        consultar.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CONSULTAR2.png"))); // NOI18N
        consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar.setOpaque(false);
        consultar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CONSULTAR.png"))); // NOI18N
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        jPanel1.add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 150, 40));

        jLabel4.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel4.setText("Fecha:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 60, -1));

        fecha.setEditable(false);
        fecha.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        fecha.setBorder(null);
        fecha.setOpaque(false);
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 160, -1));

        jScrollPane2.setOpaque(false);

        productos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));
        productos.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO UNIDAD", "SUBTOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productos.setEnabled(false);
        productos.setGridColor(new java.awt.Color(255, 255, 255));
        productos.setPreferredSize(new java.awt.Dimension(375, 200));
        productos.setSelectionBackground(new java.awt.Color(102, 0, 102));
        jScrollPane2.setViewportView(productos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 740, 230));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CERRAR2.png"))); // NOI18N
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setOpaque(false);
        cerrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CERRAR.png"))); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 130, 40));

        jLabel5.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel5.setText("Total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 460, 90, -1));

        total.setEditable(false);
        total.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        total.setBorder(null);
        total.setOpaque(false);
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
            try{
                String id = this.cotizaciones.getSelectedItem().toString();
                String[] cotizacion = controlCotizacion.consultarCotizacion(id);
            
                if (cotizacion == null) {
                    JOptionPane.showMessageDialog(this, "No se pudo consultar la cotización seleccionada");
                } else {                
                    this.cotizacion.setText(cotizacion[0]);
                    this.vendedor.setText(cotizacion[1]);
                    this.fecha.setText(cotizacion[2]);
                    this.total.setText(cotizacion[3]);
                    tabla = this.controlCarritoCot.cargarProductosCot(this.cotizacion.getText());
                    this.productos.setModel(tabla);
                }
            }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
            }
        
    }//GEN-LAST:event_consultarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.setVisible(false);
        Vendedor vendedor = new Vendedor(usuario);
        vendedor.setVisible(true);
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JButton consultar;
    private javax.swing.JTextField cotizacion;
    private javax.swing.JComboBox<String> cotizaciones;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTituloConsultarCotizacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public static javax.swing.JTable productos;
    private javax.swing.JTextField total;
    private javax.swing.JTextField vendedor;
    // End of variables declaration//GEN-END:variables
}
