/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Natalia
 */
public class eliminarCotizacion extends javax.swing.JFrame {
    String usuario;
    DefaultTableModel tabla;
    ControlCotizacion controlCotizacion = new ControlCotizacion();
    ControlCarritoCot controlCarritoCot = new ControlCarritoCot();
    /**
     * Creates new form eliminarCotizacion
     */
    public eliminarCotizacion(String usuario) {
        this.usuario = usuario;
        initComponents();
        this.setLocationRelativeTo(null);
        cargarCotizaciones("");
    }
    
    void cargarCotizaciones(String busqueda){
        tabla = controlCotizacion.cargarInfoCotizaciones(busqueda);
        this.cotizaciones.setModel(tabla);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        busqueda = new javax.swing.JTextField();
        jLabelEliminarCotizacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cotizaciones = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CERRAR2.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CERRAR.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 150, 40));

        jLabel2.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel2.setText("N° Cotizacion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        busqueda.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        busqueda.setBorder(null);
        busqueda.setOpaque(false);
        busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busquedaKeyReleased(evt);
            }
        });
        jPanel1.add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, -1));

        jLabelEliminarCotizacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEliminarCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ELIMINARCOTIZACIONFONDO.png"))); // NOI18N
        jPanel1.add(jLabelEliminarCotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -7, 570, 100));

        cotizaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));
        cotizaciones.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        cotizaciones.setForeground(new java.awt.Color(102, 0, 102));
        cotizaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° COTIZACION", "CEDULA VENDEDOR", "FECHA ", "TOTAL"
            }
        ));
        cotizaciones.setPreferredSize(new java.awt.Dimension(400, 400));
        cotizaciones.setSelectionBackground(new java.awt.Color(102, 0, 102));
        cotizaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cotizacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cotizaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 520, 240));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cotizacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cotizacionesMouseClicked
        try {
            int  fila = cotizaciones.getSelectedRow();

            String codigo = cotizaciones.getValueAt(fila, 0).toString();

            int  numero = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar la cotizacion N°"+ codigo +"?");
            if((numero == 1) || (numero == 2)){
                JOptionPane.showMessageDialog(this, "La cotizacion no fue eliminada");
            }
            else{
                String mensaje = controlCotizacion.eliminarCotizacion(codigo);
                controlCarritoCot.eliminarProductos(codigo);
                JOptionPane.showMessageDialog(this, mensaje);
                cargarCotizaciones("");
            }

        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_cotizacionesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Vendedor v = new Vendedor(usuario);
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaKeyReleased
        String busqueda = this.busqueda.getText();
        cargarCotizaciones(busqueda);
    }//GEN-LAST:event_busquedaKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busqueda;
    private javax.swing.JTable cotizaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEliminarCotizacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
