/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Natalia
 */
public class modificarCotizacion extends javax.swing.JFrame {

    /**
     * Creates new form modificarCotizacion
     */
    public modificarCotizacion() {
        initComponents();
        setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelModificarCotizacion = new javax.swing.JLabel();
        jLabelNumeroCotizacionModificar = new javax.swing.JLabel();
        jTextFieldCotizacionModificar = new javax.swing.JTextField();
        jLabelVendedorModificar = new javax.swing.JLabel();
        jTextFieldVendedorModificar = new javax.swing.JTextField();
        jLabelValorModificar = new javax.swing.JLabel();
        jTextFieldValorModificar = new javax.swing.JTextField();
        jButtonModificarCotizacion = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelModificarCotizacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelModificarCotizacion.setText("Modificar cotizacion");

        jLabelNumeroCotizacionModificar.setText("Numero cotizacion: ");

        jLabelVendedorModificar.setText("Vendedor");

        jLabelValorModificar.setText("Valor");

        jButtonModificarCotizacion.setText("Buscar");

        jButtonModificar.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelModificarCotizacion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelVendedorModificar)
                                .addComponent(jLabelValorModificar))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldVendedorModificar)
                                .addComponent(jTextFieldValorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jButtonModificar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNumeroCotizacionModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCotizacionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonModificarCotizacion)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelModificarCotizacion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroCotizacionModificar)
                    .addComponent(jTextFieldCotizacionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarCotizacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVendedorModificar)
                    .addComponent(jTextFieldVendedorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorModificar)
                    .addComponent(jTextFieldValorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonModificar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonModificarCotizacion;
    private javax.swing.JLabel jLabelModificarCotizacion;
    private javax.swing.JLabel jLabelNumeroCotizacionModificar;
    private javax.swing.JLabel jLabelValorModificar;
    private javax.swing.JLabel jLabelVendedorModificar;
    private javax.swing.JTextField jTextFieldCotizacionModificar;
    private javax.swing.JTextField jTextFieldValorModificar;
    private javax.swing.JTextField jTextFieldVendedorModificar;
    // End of variables declaration//GEN-END:variables
}
