/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultKeyedValuesDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author juandavid
 */
public class ReporteVentas extends javax.swing.JFrame {
    String usuario;
    ControlVenta controlVenta;
    /**
     * Creates new form ReporteVentas
     */
    public ReporteVentas(String usuario) {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(0);
        controlVenta = new ControlVenta();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        graficar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        start = new com.toedter.calendar.JDateChooser();
        jButtonGenerarTabla = new javax.swing.JButton();
        end = new com.toedter.calendar.JDateChooser();
        vendedores = new javax.swing.JRadioButton();
        sedes = new javax.swing.JRadioButton();
        pastel = new javax.swing.JRadioButton();
        barras = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        reporte = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ganacias = new javax.swing.JRadioButton();
        productos = new javax.swing.JRadioButton();
        reporteAnual = new javax.swing.JToggleButton();
        año = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REPORTES");

        graficar.setText("Graficar");
        graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficarActionPerformed(evt);
            }
        });

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jButtonGenerarTabla.setText("Generar");
        jButtonGenerarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarTablaActionPerformed(evt);
            }
        });

        buttonGroup1.add(vendedores);
        vendedores.setText("Vendedor");

        buttonGroup1.add(sedes);
        sedes.setText("Sedes");
        sedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedesActionPerformed(evt);
            }
        });

        buttonGroup2.add(pastel);
        pastel.setText("Pastel");

        buttonGroup2.add(barras);
        barras.setText("Barras");
        barras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barrasActionPerformed(evt);
            }
        });

        reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(reporte);

        jLabel2.setText("Fecha inicial:");

        jLabel3.setText("Fecha final:");

        buttonGroup1.add(ganacias);
        ganacias.setText("Ganacias");

        buttonGroup1.add(productos);
        productos.setText("Productos");

        reporteAnual.setText("Reporte de ganancias anual");
        reporteAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteAnualActionPerformed(evt);
            }
        });

        año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sedes)
                                .addGap(18, 18, 18)
                                .addComponent(vendedores)
                                .addGap(18, 18, 18)
                                .addComponent(ganacias)
                                .addGap(18, 18, 18)
                                .addComponent(productos))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonGenerarTabla)
                                    .addGap(18, 18, 18)
                                    .addComponent(reporteAnual)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                    .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(barras)
                                    .addGap(18, 18, 18)
                                    .addComponent(pastel)
                                    .addGap(32, 32, 32)
                                    .addComponent(graficar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cerrar))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addComponent(jLabel3))
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(end, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                        .addComponent(start, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sedes)
                    .addComponent(vendedores)
                    .addComponent(ganacias)
                    .addComponent(productos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerarTabla)
                    .addComponent(reporteAnual)
                    .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barras)
                    .addComponent(pastel)
                    .addComponent(graficar)
                    .addComponent(cerrar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficarActionPerformed
        try{
            int filas = reporte.getRowCount();
            String titulo = reporte.getColumnName(1) + " POR " + reporte.getColumnName(0); //titulo de la tabla

        
            if(barras.isSelected()){
                DefaultCategoryDataset data = new DefaultCategoryDataset();
                for (int i=0; i < filas; i++){
                    data.setValue(Integer.parseInt(reporte.getValueAt(i, 1).toString()),reporte.getValueAt(i, 0).toString(),reporte.getValueAt(i, 0).toString()); //captura de datos de la tabla para nombre de valores variables.
                }
                JFreeChart grafica = ChartFactory.createBarChart3D(titulo,reporte.getColumnName(0), reporte.getColumnName(1), data, PlotOrientation.VERTICAL, true, true, true); //nombre de valores variables
                ChartFrame panelGrafica = new ChartFrame(titulo, grafica);
                panelGrafica.setSize(600,600);
                panelGrafica.setLocationRelativeTo(null);
                panelGrafica.setVisible(true);

                String [] Titulo = {};
                DefaultTableModel newTabla = new DefaultTableModel(null,Titulo);
                this.reporte.setModel(newTabla);
            }
            if(pastel.isSelected()){
                DefaultPieDataset data = new DefaultKeyedValuesDataset();
                for (int i=0; i < filas; i++){
                    data.setValue(reporte.getValueAt(i, 0).toString(), Integer.parseInt(reporte.getValueAt(i, 1).toString()));//captura de datos de la tabla para nombre de valores manual.
                }
                JFreeChart grafica = ChartFactory.createPieChart(titulo, data, true, true,true); //nombres de valores manuales.
                ChartFrame panelGrafica = new ChartFrame(titulo, grafica);
                panelGrafica.setSize(600,600);
                panelGrafica.setLocationRelativeTo(null);
                panelGrafica.setVisible(true);

                String [] Titulo = {};
                DefaultTableModel newTabla = new DefaultTableModel(null,Titulo);
                this.reporte.setModel(newTabla);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
        }
    }//GEN-LAST:event_graficarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        Menu_Gerente u = new Menu_Gerente(usuario);
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cerrarActionPerformed

    private void jButtonGenerarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarTablaActionPerformed
        try{
            DefaultTableModel tabla;
            String start = this.start.getDate().toString();
            String end = this.end.getDate().toString();
            if(sedes.isSelected()){
                tabla = controlVenta.ventasSede(start,end);
                reporte.setModel(tabla);
            }
            if(vendedores.isSelected()){
                tabla = controlVenta.ventasVendedor(start,end);
                reporte.setModel(tabla);
            }
            if(ganacias.isSelected()){
                tabla = controlVenta.gananciasSedes(start,end);
                reporte.setModel(tabla);
            }
            if(productos.isSelected()){
                tabla = controlVenta.productosVendidos(start,end);
                reporte.setModel(tabla);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonGenerarTablaActionPerformed

    private void sedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedesActionPerformed

    private void barrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barrasActionPerformed

    private void reporteAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteAnualActionPerformed
        try{
            DefaultTableModel tabla;
            String year = this.año.getSelectedItem().toString();
            tabla = controlVenta.gananciaAnual(year);
            reporte.setModel(tabla);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
        }
    }//GEN-LAST:event_reporteAnualActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> año;
    private javax.swing.JRadioButton barras;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cerrar;
    private com.toedter.calendar.JDateChooser end;
    private javax.swing.JRadioButton ganacias;
    private javax.swing.JButton graficar;
    private javax.swing.JButton jButtonGenerarTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton pastel;
    private javax.swing.JRadioButton productos;
    private javax.swing.JTable reporte;
    private javax.swing.JToggleButton reporteAnual;
    private javax.swing.JRadioButton sedes;
    private com.toedter.calendar.JDateChooser start;
    private javax.swing.JRadioButton vendedores;
    // End of variables declaration//GEN-END:variables
}
