/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultKeyedValuesDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author juandavid
 */
public class ReporteVentas extends javax.swing.JFrame {
    String usuario;
    ControlVenta controlVenta;
    /**
     * Creates new form ReporteVentas
     */
    public ReporteVentas(String usuario) {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(0);
        controlVenta = new ControlVenta();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sedes = new javax.swing.JRadioButton();
        vendedores = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        start = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        end = new com.toedter.calendar.JDateChooser();
        jButtonGenerarTabla = new javax.swing.JButton();
        reporteAnual = new javax.swing.JToggleButton();
        año = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        reporte = new javax.swing.JTable();
        barras = new javax.swing.JRadioButton();
        pastel = new javax.swing.JRadioButton();
        cerrar = new javax.swing.JButton();
        graficar = new javax.swing.JButton();
        ganacias = new javax.swing.JRadioButton();
        productos = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ReporteEncabezado.png"))); // NOI18N

        sedes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(sedes);
        sedes.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        sedes.setForeground(new java.awt.Color(128, 49, 145));
        sedes.setText("Venta por sedes");
        sedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedesActionPerformed(evt);
            }
        });

        vendedores.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(vendedores);
        vendedores.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        vendedores.setForeground(new java.awt.Color(128, 49, 145));
        vendedores.setText("Venta por vendedor");

        jLabel2.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(128, 49, 145));
        jLabel2.setText("Fecha inicial:");

        start.setBackground(new java.awt.Color(255, 255, 255));
        start.setForeground(new java.awt.Color(128, 49, 145));

        jLabel3.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 49, 145));
        jLabel3.setText("Fecha final:");

        end.setBackground(new java.awt.Color(255, 255, 255));
        end.setForeground(new java.awt.Color(128, 49, 145));

        jButtonGenerarTabla.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGenerarTabla.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jButtonGenerarTabla.setForeground(new java.awt.Color(128, 49, 145));
        jButtonGenerarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgreagarReporte.png"))); // NOI18N
        jButtonGenerarTabla.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonGenerarTabla.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgreagarReporte2.png"))); // NOI18N
        jButtonGenerarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarTablaActionPerformed(evt);
            }
        });

        reporteAnual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GananciaAnual2.png"))); // NOI18N
        reporteAnual.setPreferredSize(new java.awt.Dimension(300, 25));
        reporteAnual.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GananciaAnual.png"))); // NOI18N
        reporteAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteAnualActionPerformed(evt);
            }
        });

        año.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        año.setForeground(new java.awt.Color(128, 49, 145));
        año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022" }));
        año.setPreferredSize(new java.awt.Dimension(49, 25));

        reporte.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        reporte.setForeground(new java.awt.Color(128, 49, 145));
        reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(reporte);

        barras.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(barras);
        barras.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        barras.setForeground(new java.awt.Color(128, 49, 145));
        barras.setText("Barras");
        barras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barrasActionPerformed(evt);
            }
        });

        pastel.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(pastel);
        pastel.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        pastel.setForeground(new java.awt.Color(128, 49, 145));
        pastel.setText("Pastel");

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CerrarRepo.png"))); // NOI18N
        cerrar.setPreferredSize(new java.awt.Dimension(100, 25));
        cerrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CerrarRepo2.png"))); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        graficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Graficar.png"))); // NOI18N
        graficar.setPreferredSize(new java.awt.Dimension(100, 25));
        graficar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Graficar2.png"))); // NOI18N
        graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficarActionPerformed(evt);
            }
        });

        ganacias.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(ganacias);
        ganacias.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        ganacias.setForeground(new java.awt.Color(128, 49, 145));
        ganacias.setText("Ganancias por sede");

        buttonGroup1.add(productos);
        productos.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        productos.setForeground(new java.awt.Color(128, 49, 145));
        productos.setText("Unidades vendidas por producto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(barras)
                                    .addGap(18, 18, 18)
                                    .addComponent(pastel)
                                    .addGap(49, 49, 49)
                                    .addComponent(graficar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(67, 67, 67)
                                    .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonGenerarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reporteAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(año, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ganacias)
                            .addComponent(sedes))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vendedores)
                            .addComponent(productos))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sedes)
                    .addComponent(vendedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ganacias)
                    .addComponent(productos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonGenerarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reporteAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barras)
                        .addComponent(pastel)
                        .addComponent(graficar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficarActionPerformed
        try{
            int filas = reporte.getRowCount();
            String titulo = reporte.getColumnName(1) + " POR " + reporte.getColumnName(0); //titulo de la tabla

        
            if(barras.isSelected()){
                DefaultCategoryDataset data = new DefaultCategoryDataset();
                for (int i=0; i < filas; i++){
                    data.setValue(Integer.parseInt(reporte.getValueAt(i, 1).toString()),reporte.getValueAt(i, 0).toString(),reporte.getValueAt(i, 0).toString()); //captura de datos de la tabla para nombre de valores variables.
                }
                JFreeChart grafica = ChartFactory.createBarChart3D(titulo,reporte.getColumnName(0), reporte.getColumnName(1), data, PlotOrientation.VERTICAL, true, true, true); //nombre de valores variables
                ChartFrame panelGrafica = new ChartFrame(titulo, grafica);
                panelGrafica.setSize(800,600);
                panelGrafica.setLocationRelativeTo(null);
                panelGrafica.setVisible(true);

                String [] Titulo = {};
                DefaultTableModel newTabla = new DefaultTableModel(null,Titulo);
                this.reporte.setModel(newTabla);
            }
            if(pastel.isSelected()){
                DefaultPieDataset data = new DefaultKeyedValuesDataset();
                for (int i=0; i < filas; i++){
                    data.setValue(reporte.getValueAt(i, 0).toString(), Integer.parseInt(reporte.getValueAt(i, 1).toString()));//captura de datos de la tabla para nombre de valores manual.
                }
                JFreeChart grafica = ChartFactory.createPieChart(titulo, data, true, true,true); //nombres de valores manuales.
                ChartFrame panelGrafica = new ChartFrame(titulo, grafica);
                panelGrafica.setSize(800,600);
                panelGrafica.setLocationRelativeTo(null);
                panelGrafica.setVisible(true);

                String [] Titulo = {};
                DefaultTableModel newTabla = new DefaultTableModel(null,Titulo);
                this.reporte.setModel(newTabla);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
        }
    }//GEN-LAST:event_graficarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        Menu_Gerente u = new Menu_Gerente(usuario);
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cerrarActionPerformed

    private void jButtonGenerarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarTablaActionPerformed
        try{
            DefaultTableModel tabla;
            String start = this.start.getDate().toString();
            String end = this.end.getDate().toString();
            if(sedes.isSelected()){
                tabla = controlVenta.ventasSede(start,end);
                reporte.setModel(tabla);
            }
            if(vendedores.isSelected()){
                tabla = controlVenta.ventasVendedor(start,end);
                reporte.setModel(tabla);
            }
            if(ganacias.isSelected()){
                tabla = controlVenta.gananciasSedes(start,end);
                reporte.setModel(tabla);
            }
            if(productos.isSelected()){
                tabla = controlVenta.productosVendidos(start,end);
                reporte.setModel(tabla);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonGenerarTablaActionPerformed

    private void sedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedesActionPerformed

    private void barrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barrasActionPerformed

    private void reporteAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteAnualActionPerformed
        try{
            DefaultTableModel tabla;
            String year = this.año.getSelectedItem().toString();
            tabla = controlVenta.gananciaAnual(year);
            reporte.setModel(tabla);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al capturar los datos");
            System.out.println(e);
        }
    }//GEN-LAST:event_reporteAnualActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> año;
    private javax.swing.JRadioButton barras;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cerrar;
    private com.toedter.calendar.JDateChooser end;
    private javax.swing.JRadioButton ganacias;
    private javax.swing.JButton graficar;
    private javax.swing.JButton jButtonGenerarTabla;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton pastel;
    private javax.swing.JRadioButton productos;
    private javax.swing.JTable reporte;
    private javax.swing.JToggleButton reporteAnual;
    private javax.swing.JRadioButton sedes;
    private com.toedter.calendar.JDateChooser start;
    private javax.swing.JRadioButton vendedores;
    // End of variables declaration//GEN-END:variables
}
